<a href="https://colab.research.google.com/github/UUbaidurRehman/ML_DL/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# import numpy as np

In [ ]:
np.__version__
# np.__version__

'2.0.2'

# **Creating a numpy array**

In [ ]:
# fromm python list to np.array
list1 = [1,2,3,4,5,6,7,8,9,10]

print("list = ", list1)
print("type of list = ", type(list1))

list2 = np.array(list1)
print(f"numpy array = {list2}", type(list2))

list =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
type of list =  <class 'list'>
numpy array = [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [ ]:
np.array(list1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2D array / matrix
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Operations**

In [ ]:
#Addition of simple list vs np.array
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,15,16,17,18,19,20]
print(list1+list2)
list1 = np.array(list1)
list2 = np.array(list2)
print("use of + on numpy array = ", list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use of + on numpy array =  [12 14 16 18 20 22 24 26 28 30]


In [ ]:
import time
begin = time.time()
listA = list(range(1000000))
listB = list(range(1000000))
result = []
start = time.time()
for i in range(len(listA)):
  result.append(listA[i] + listB[i])
end = time.time()
print("addition of lists time:      ", end - start)
arrayA = np.array (listA)
arrayB = np.array (listB)
start = time.time()
result = arrayA + arrayB
end = time.time()
print("addition of NUmpy array time:", end - start)
final = time.time()
print(final- begin)

addition of lists time:       0.3452625274658203
addition of NUmpy array time: 0.05959296226501465
0.8641927242279053


In [ ]:
import time
listA = list(range(10000000))
listB = list(range(10000000))
start = time.time()
result = []
for i in range(len(listA)):
    result.append((listA[i]  + listB[i]))
end = time.time()
print("time taken = ", end-start)

listA = np.array(listA)
listB = np.array(listB)
start = time.time()
result = listA + listB
end = time.time()
print("time taken by numpy array ", end - start)

time taken =  3.551345109939575
time taken by numpy array  0.19345545768737793


In [ ]:
print(list(range(0,100,5)))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


array with **zeros, and ones**

In [ ]:
print(np.zeros(3))
print(np.zeros((2,4)))
print(np.ones(5))
print(np.ones((5,5)))

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# **arange:**
spaced values in array with given interval

In [ ]:
#start, stop, and step
print(np.arange(0,10))
print(np.arange(0,50,6))

[0 1 2 3 4 5 6 7 8 9]
[ 0  6 12 18 24 30 36 42 48]


# **Linspace**:
spaced number of values

In [ ]:
#start,inclusive stop,number of values
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# **eye and identity**

In [ ]:
print(np.eye(2,3))

print("identity")
print(np.identity(5))
#both produce 1's in diagonal, eye is flexible on size and shape, while identity is square shaped
print(np.eye(1))

[[1. 0. 0.]
 [0. 1. 0.]]
identity
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1.]]


# **Random Array**

In [ ]:
import random
number = random.randint(0,100)
print (number)
number = random.random() # floating point no.
print (number)
listR = [random.randint(0,100) for _ in range(10)] #list comprehension to generate a list of 10 random intergers between 0 to 100
print(listR)

73
0.8828063964102224
[94, 19, 8, 91, 8, 86, 10, 85, 28, 2]


In [ ]:
random.randint(0,100)

19

In [ ]:
D1 = np.random.randint(0,10,9)
print(D1)

[1 2 2 6 5 5 3 6 1]


In [ ]:
rand1 = np.random.randint (0,10,4)
print(rand1)
print(np.random.randint(0,19,(2,5)))
print(np.random.rand(2,5))

[8 2 0 0]
[[12  7  1 14 13]
 [18 12  6 13 10]]
[[0.96664334 0.319241   0.15148754 0.56339923 0.64833075]
 [0.99919688 0.93847952 0.49580148 0.12663972 0.54609635]]


# **Indexing**

In [ ]:
D1[5] # 5th index

np.int64(5)

In [ ]:
D1[2:5]

array([2, 6, 5])

In [ ]:
D1[5:2:-1]

array([5, 5, 6])

In [ ]:
D2 = np.random.randint(0,1,(2,3))

[[23  6 24  3 30]
 [31  9  8 16 34]
 [12 35 36 16 11]
 [ 9 19 19  7  2]]
[31  9  8 16 34]


In [ ]:
#random with Standard normal distribution
np.random.randn(4,3)

array([[ 0.74968245,  0.55624563,  0.76080415],
       [-1.27965782, -0.88059169, -1.22396198],
       [-0.03133445, -1.37123689, -0.77602033],
       [ 3.17079311,  0.18952125,  1.84100261]])

In [ ]:
#random array 2d with 4 rows and 3 columns
play = np.random.rand(4,3)
print(play)

[[0.50025982 0.94411615 0.33788421]
 [0.02492239 0.35875746 0.45597763]
 [0.47343718 0.37071157 0.33381367]
 [0.66393189 0.63620464 0.85882819]]


In [ ]:
play.reshape(1,12)

array([[0.50025982, 0.94411615, 0.33788421, 0.02492239, 0.35875746,
        0.45597763, 0.47343718, 0.37071157, 0.33381367, 0.66393189,
        0.63620464, 0.85882819]])

In [ ]:
play.T

array([[0.50025982, 0.02492239, 0.47343718, 0.66393189],
       [0.94411615, 0.35875746, 0.37071157, 0.63620464],
       [0.33788421, 0.45597763, 0.33381367, 0.85882819]])

In [ ]:
play

array([[0.50025982, 0.94411615, 0.33788421],
       [0.02492239, 0.35875746, 0.45597763],
       [0.47343718, 0.37071157, 0.33381367],
       [0.66393189, 0.63620464, 0.85882819]])

In [ ]:
play.dtype

dtype('float64')

# **Revisting conepts**

1.   Install, import and check version
2.   Different ways of creating a numpy array, check type
3.   Creating 1,2,3 and multi dimension array
4.   Create array with zeros and Ones.  
5.   Create array with unitialzed values, and with constant (empty,full)
6.   Create a 1,2-D identity, and a flexible identity array (eye, identity)
7.   Create an array with spaced elements  ( arange, linspace)
8.   Create array with random intergers in a range (random, mean,std)
9.   Change array value type with astype()
10.  Can i loop over a numpy array?
11.  Perform operations add, subs, multiply, div
12.  Accessing elements of numpy array

In [ ]:
# Install, import and check version
!pip install numpy

In [ ]:
import numpy as np
np.__version__

'2.0.2'

## Different ways of creating a numpy array.
*create array with empty, zeros, ones,constant values, eye, identity, arange, linspace, random number(int,float)*

In [ ]:
# Create with list and tuple
listarray = np.array([2,34,1,1]) #list
print(listarray)
tuplearray = np.array((1,4,2,6,2))
print(tuplearray)

[ 2 34  1  1]
[1 4 2 6 2]


In [ ]:
# create with zero's, one's
#
d1zeroarray = np.zeros(5)
print("1-D zeroarray")
print(d1zeroarray)
zeroarray = np.zeros(5, int)
print("1-D zeroarray with data types specified")
print(zeroarray)
zeroarray = np.zeros((3,4)) #2D array with tuple of int
print("2D zeroarray")
print(zeroarray)
onearray  = np.ones((2,5),int)
print("2D onearray with data type\n",onearray)

1-D zeroarray
[0. 0. 0. 0. 0.]
1-D zeroarray with data types specified
[0 0 0 0 0]
2D zeroarray
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D onearray with data type
 [[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#create array with empty
emptyarray = np.empty(5)
print(emptyarray)
emptyarray = np.empty((3,4))
print("emptyarray with shape\n", emptyarray)

[0. 0. 0. 0. 0.]
emptyarray with shape
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# create  a filed array with constant
constantnoarray = np.full((4,4),3)
print(constantnoarray)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
# create array with eye and identity
identityarray = np.identity(5,int)
print(identityarray)
eyearray= np.eye(5,3)
eyearray

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# arange and linspace
arangearray = np.arange(2 , 20 ,3) #start, stop,step
print(arangearray )
linspacearray = np.linspace(3,13,5) #start,stop, no. of values required
linspacearray

[ 2  5  8 11 14 17]


array([ 3. ,  5.5,  8. , 10.5, 13. ])

In [ ]:
# random array
randomarray = np.random.randint(3,8, (3,3))
print(randomarray)

[[6 4 6]
 [4 7 5]
 [3 3 5]]


In [ ]:
# dimensional Arrays
arr1d = np.array ( [2,34,5,65,1])
arr2d = np.array ([[2,3,4],[4,6,7]])

arr = np.array([[[23,24,1],[54,23,7]],
                  [[8,12,4],[3,2,0]]
                ])
print(arr1d.ndim)
print(arr2d.ndim)
print(arr.ndim)
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

1
2
3
[[[[[1 2 3 4]]]]]


In [ ]:
# !pip install numpy
import numpy as np
# np.__version__
array1 = np.array([1,2,35,6,1,3])
array2 = np.array((2,35,32,13,))
array3 = np.zeros((4,5)) # only (5) means 1x5 i..e 5 values in 1D array
array4 = np.ones(4,int) # 1x4 values of interger type, bydefault its float type for ones and zeros
array5 = np.empty(3)
# filed with constant, eye,identity
array6 = np.full([5,1],45)
array7 = np.eye(N=6,M= 6,k=0, dtype=int)
array8 = np.identity(5,dtype= int)
array9 = np.arange(0,40,7)
array10 = np.linspace(0,40,10,dtype= int)


In [ ]:
#print type of array1 and convert to someother datatype with (astype)
print(array1.dtype)
np.astype(array1, np.float64 ) # copy array one, convert values to float )

int64


array([ 1.,  2., 35.,  6.,  1.,  3.])

In [ ]:
array11 = np.random.rand(2,3)
array12 = np.random.randint(low=3, high= 12, size=[3,5,2],)
# standard deviation with random randn, test other randoms
array13 = np.random.randn(12,3,)
array14 = 3 + 2.5 *(np.random.randn(4,3))
print(array14)
print(np.mean(array14))
print(np.std(array14))
np.random.choice(10,5,0) #stop,no. of values, 0 = no repeat | 1 =repeat

[[-0.52939887  5.33103102  2.69898593]
 [ 4.82138526  4.0499282   0.12234962]
 [ 5.59049051 -1.65997604  2.97859874]
 [ 0.8526689   3.17883413  1.39662565]]
2.402626921283852
2.2737575205953786


array([5, 8, 1, 4, 0])

In [ ]:
# Want to reproduce same results with random
np.random.seed(42) #set a seed
array15 = np.random.rand(3)

array16 = np.random.rand(3)

#activate same seed again
np.random.seed(42)
array17 = np.random.rand(3)


In [ ]:
print('array15 with seed(42): ', array15)
print('array16 without seed: ', array16)
print('array17 with same seed(42): ', array17)

array15 with seed(42):  [0.37454012 0.95071431 0.73199394]
array16 without seed:  [0.59865848 0.15601864 0.15599452]
array17 with same seed(42):  [0.37454012 0.95071431 0.73199394]


Operations:

*   size, shape, max , min, argmax argmin
*   mean , median , prod, sum, std
*   reshape , transform, T
*   






In [ ]:
print(array1)
print(array1.size, array1.shape)

print (str(np.max(array1)) + " index of max value " + str(np.argmax(array1)))
min_array1 = (np.min(array1))
index_min_array1 = np.argmin(array1)
print(f"Minimum value in array 1 is {min_array1} and its index is {index_min_array1}")

sum_array1 = np.sum(array1)
product_array1 = np.prod(array1)
print(f"the sum of array1 values is {sum_array1} and product of array1 values is {product_array1}")
print(np.mean(array1))
print(np.median(array1))
print(np.std(array1))


[ 1  2 35  6  1  3]
6 (6,)
35 index of max value 2
Minimum value in array 1 is 1 and its index is 0
the sum of array1 values is 48 and product of array1 values is 1260
8.0
2.5
12.192894105447921


In [ ]:
randarray = np.random.randint(low = 0, high = 50, size = 15)
print(randarray)
print(randarray.shape)
rerandarray = randarray.reshape(3,5)
print(rerandarray)
print(rerandarray.shape)
print(rerandarray.size)

[20 38 18 22 10 10 23 35 39 23  2 21  1 23 43]
(15,)
[[20 38 18 22 10]
 [10 23 35 39 23]
 [ 2 21  1 23 43]]
(3, 5)
15


In [ ]:
# transpose and T on 1-D array
print(np.transpose(randarray))
print(randarray.T)

[20 38 18 22 10 10 23 35 39 23  2 21  1 23 43]
[20 38 18 22 10 10 23 35 39 23  2 21  1 23 43]


In [ ]:
# Transpose and T on 2-D array
Transposedarray = rerandarray.T
print(Transposedarray)
print(Transposedarray[1][1])

[[20 10  2]
 [38 23 21]
 [18 35  1]
 [22 39 23]
 [10 23 43]]
23


# **Indexing and Slicing**

In [ ]:
# Accessing a slice of a 2D array
print(Transposedarray)
print(Transposedarray[1:3, 0:2]) # This slices rows from index 1 up to (but not including) index 3, and columns from index 0 up to (but not including) index 2.

[[20 10  2]
 [38 23 21]
 [18 35  1]
 [22 39 23]
 [10 23 43]]
[[38 23]
 [18 35]]


In [ ]:
print(Transposedarray[:, 1]) #get column 1 values of all the rows

[[ 3 18 17 13  1]
 [14 21  6 17 20]
 [13 20  2 11  5]
 [12 37  3 18  0]]
[18 21 20 37]


In [ ]:
print(Transposedarray[0:3,2])

[ 2 21  1]


In [ ]:
print(Transposedarray.flatten(order='C')) # row major
print(Transposedarray.ravel())
print(Transposedarray.flat[14]) #flat gets the element
print(Transposedarray.flatten(order = 'F')) # column major

[20 10  2 38 23 21 18 35  1 22 39 23 10 23 43]
[20 10  2 38 23 21 18 35  1 22 39 23 10 23 43]
43
[20 38 18 22 10 10 23 35 39 23  2 21  1 23 43]


In [ ]:
import numpy as np
test_column = np.random.randint(0,40,(4,5))
print (test_column)
print(test_column[:][1])

# Concatenate and split

In [ ]:

concate_array = np.concatenate((array1,randarray), axis = 0)
print(concate_array)
arr1 = np.random.randint(0,40,10)
arr2 = np.random.randint(40,80,10)
print(arr1,arr2)
concate_array12 = np.concatenate((arr1,arr2),axis = 0)
print (concate_array12)
# Reshape 1D arrays to 2D arrays before concatenating along axis=1
concate_array12 = np.concatenate((arr1.reshape(-1, 1), arr2.reshape(-1, 1)), axis=1)
print (concate_array12)

[ 1  2 35  6  1  3 20 38 18 22 10 10 23 35 39 23  2 21  1 23 43]
[29 37  1 20 32 11 21 24 26 27] [55 54 42 76 46 60 48 78 57 43]
[29 37  1 20 32 11 21 24 26 27 55 54 42 76 46 60 48 78 57 43]
[[29 55]
 [37 54]
 [ 1 42]
 [20 76]
 [32 46]
 [11 60]
 [21 48]
 [24 78]
 [26 57]
 [27 43]]


In [ ]:
arr1.reshape(-1, 1)

array([[29],
       [37],
       [ 1],
       [20],
       [32],
       [11],
       [21],
       [24],
       [26],
       [27]])

In [ ]:
picture1 = np.random.randint(0,50,(5,6))
picture2 = np.random.randint(50,100,(5,6))
print(picture1, " \n")
print(picture2, " \n")
con_picture = np.concatenate((picture1,picture2),axis = 0)
print(con_picture)
con_picture = np.concatenate((picture1,picture2),axis = 1)
print(con_picture)

[[24 13 49  8 25  1]
 [19 27 46  6 43  7]
 [46 34 13 16 35 49]
 [39  3  1  5 41  3]
 [28 17 25 43 33  9]]  

[[85 63 80 97 64 57]
 [63 72 89 70 65 94]
 [67 96 73 75 74 94]
 [90 78 64 94 50 74]
 [56 58 73 50 93 57]]  

[[24 13 49  8 25  1]
 [19 27 46  6 43  7]
 [46 34 13 16 35 49]
 [39  3  1  5 41  3]
 [28 17 25 43 33  9]
 [85 63 80 97 64 57]
 [63 72 89 70 65 94]
 [67 96 73 75 74 94]
 [90 78 64 94 50 74]
 [56 58 73 50 93 57]]
[[24 13 49  8 25  1 85 63 80 97 64 57]
 [19 27 46  6 43  7 63 72 89 70 65 94]
 [46 34 13 16 35 49 67 96 73 75 74 94]
 [39  3  1  5 41  3 90 78 64 94 50 74]
 [28 17 25 43 33  9 56 58 73 50 93 57]]


In [ ]:
# split()
a,b  = np.split(con_picture, 2, axis=1 )
a.flatten(order = 'C')
# a,b,c,d,e,f = np.split(con_picture, 6, axis=1)
# a
# argmax, argmin

array([24, 13, 49,  8, 25,  1, 19, 27, 46,  6, 43,  7, 46, 34, 13, 16, 35,
       49, 39,  3,  1,  5, 41,  3, 28, 17, 25, 43, 33,  9])

# 4. Mathematical & Statistical Operations

Element-wise: +, -, *, /, **

np.add(), np.multiply()

In [ ]:
array1 = np.random.randint(5,20, 7)
array2 = np.random.randint(20,35,7)
array3 = np.random.randint(20,35,2)
print (array1)
print (array2)
print (array3)

[ 7  5  7  9 19 18  7]
[20 24 29 26 34 33 26]
[30 28]


In [ ]:

plus_equal = array1 + array2
plus_not_equal = array1 ** 2
print(plus_equal)
print(plus_not_equal)

[27 29 36 35 53 51 33]
[ 49  25  49  81 361 324  49]


In [ ]:
np.add(array1, array2,)

array([27, 29, 36, 35, 53, 51, 33])

Tasks taken from prework numpy notebook attached in: <br>https://developers.google.com/machine-learning/crash-course/prereqs-and-prework

# Task 1: Create a Linear Dataset
Your goal is to create a simple dataset consisting of a single feature and a label as follows:
1.   Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
2.   Assign 15 values to a NumPy array named label such that:<br>
label = (3)(feature) + 4 <br>
The first value for label should be:   label = (3)(6) + 4 = 22

In [ ]:
import numpy as np
feature = np.arange(6,21)

In [ ]:
feature

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# label = (3)(feature) + 4
label = np.array([])
for i in feature :
  label = np.append(label, (3*i+4))
label

array([22., 25., 28., 31., 34., 37., 40., 43., 46., 49., 52., 55., 58.,
       61., 64.])

In [ ]:
label1 = (3 * feature) + 4
label1

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

# Task 2: Add Some Noise to the Dataset
To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created.<br> To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array having the same dimension as label. <br>
noise = ?    # write your code here <br>
print(noise) <br>
label = ?    # write your code here
print(label)

In [ ]:
size = label1.size
noise = (np.random.randn(size) * 4 ) -2
print(noise )
label1 = label1 + noise
print(label1)

[-0.67631978  2.50949573 -4.26475039 -0.85965132 -5.1144795  -1.86409123
 -9.19968479  7.30802989 -7.77520562 -4.01136808  2.58279181 -3.1373614
  2.66755059 -0.76232225 -2.0345597 ]
[21.32368022 27.50949573 23.73524961 30.14034868 28.8855205  35.13590877
 30.80031521 50.30802989 38.22479438 44.98863192 54.58279181 51.8626386
 60.66755059 60.23767775 61.9654403 ]
