<a href="https://colab.research.google.com/github/UUbaidurRehman/ML_DL/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# import numpy as np

In [ ]:
np.__version__
# np.__version__

'2.0.2'

Creating a numpy array

In [ ]:
# fromm python list to np.array
list1 = [1,2,3,4,5,6,7,8,9,10]

print("list = ", list1)
print("type of list = ", type(list1))

list2 = np.array(list1)
print(f"numpy array = {list2}", type(list2))

list =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
type of list =  <class 'list'>
numpy array = [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [ ]:
np.array(list1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2D array / matrix
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Operations

In [ ]:
#Addition of simple list vs np.array
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [11,12,13,14,15,16,17,18,19,20]
print(list1+list2)
list1 = np.array(list1)
list2 = np.array(list2)
print("use of + on numpy array = ", list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
use of + on numpy array =  [12 14 16 18 20 22 24 26 28 30]


In [ ]:
import time
begin = time.time()
listA = list(range(1000000))
listB = list(range(1000000))
result = []
start = time.time()
for i in range(len(listA)):
  result.append(listA[i] + listB[i])
end = time.time()
print("addition of lists time:      ", end - start)
arrayA = np.array (listA)
arrayB = np.array (listB)
start = time.time()
result = arrayA + arrayB
end = time.time()
print("addition of NUmpy array time:", end - start)
final = time.time()
print(final- begin)

addition of lists time:       0.16256356239318848
addition of NUmpy array time: 0.01203465461730957
0.35826635360717773


In [ ]:
import time
listA = list(range(10000000))
listB = list(range(10000000))
start = time.time()
result = []
for i in range(len(listA)):
    result.append((listA[i]  + listB[i]))
end = time.time()
print("time taken = ", end-start)

listA = np.array(listA)
listB = np.array(listB)
start = time.time()
result = listA + listB
end = time.time()
print("time taken by numpy array ", end - start)

time taken =  1.701733112335205
time taken by numpy array  0.13205647468566895


In [ ]:
print(list(range(0,100,5)))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


arange: spaced values in array with given interval

In [ ]:
#start, stop, and step
print(np.arange(0,10))
print(np.arange(0,50,6))

[0 1 2 3 4 5 6 7 8 9]
[ 0  6 12 18 24 30 36 42 48]


array with zeros, and ones

In [ ]:
print(np.zeros(3))
print(np.zeros((2,4)))
print(np.ones(5))
print(np.ones((5,5)))

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Linspace: spaced number of values

In [ ]:
#start,inclusive stop,number of values
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

eye and identity

In [ ]:
print(np.eye(2,3))

print("identity")
print(np.identity(5))
#both produce 1's in diagonal, eye is flexible on size and shape, while identity is square shaped
print(np.eye(1))

[[1. 0. 0.]
 [0. 1. 0.]]
identity
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1.]]


Random

In [ ]:
import random
number = random.randint(0,100)
print (number)
number = random.random() # floating point no.
print (number)
listR = [random.randint(0,100) for _ in range(10)] #list comprehension to generate a list of 10 random intergers between 0 to 100
print(listR)

99
0.7417821128643081
[10, 21, 79, 45, 1, 46, 56, 19, 7, 6]


In [ ]:
random.randint(0,100)

51

In [ ]:
D1 = np.random.randint(0,10,9)
print(D1)

[6 4 3 9 9 1 9 2 2]


In [ ]:
rand1 = np.random.randint (0,10,4)
print(rand1)
print(np.random.randint(0,19,(2,5)))
print(np.random.rand(2,5))

[6 4 6 8]
[[ 7 11  2  8  5]
 [17  9  1  6  0]]
[[0.6225604  0.62830043 0.2165749  0.99108909 0.37882884]
 [0.1044495  0.87923718 0.8944452  0.16620407 0.94387411]]


Indexing

In [ ]:
D1[5] # 5th index

np.int64(1)

In [ ]:
D1[2:5]

array([3, 9, 9])

In [ ]:
D1[5:2:-1]

array([1, 9, 9])

In [ ]:
D2 = np.random.randint(0,1,(2,3))

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#random with Standard normal distribution
np.random.randn(4,3)

array([[ 1.01259542,  0.02153571,  0.83666849],
       [-0.88062216,  0.34079453,  0.63013028],
       [-0.18103812, -0.46861819, -0.36846775],
       [-1.65242104, -0.3332004 , -0.10023827]])

In [ ]:
#random array 2d with 4 rows and 3 columns
play = np.random.rand(4,3)
print(play)

[[0.79696035 0.9833976  0.30897678]
 [0.50188172 0.7207822  0.72686153]
 [0.33382808 0.71212606 0.8554655 ]
 [0.97163692 0.78111996 0.63424175]]


In [ ]:
play.reshape(1,12)

array([[0.79696035, 0.9833976 , 0.30897678, 0.50188172, 0.7207822 ,
        0.72686153, 0.33382808, 0.71212606, 0.8554655 , 0.97163692,
        0.78111996, 0.63424175]])

In [ ]:
play.T

array([[0.97172669, 0.79502396, 0.17148632, 0.8485364 ],
       [0.35566456, 0.94715249, 0.52198012, 0.20665538],
       [0.80829524, 0.67198139, 0.45893516, 0.75978627]])

In [ ]:
play

array([[0.97172669, 0.35566456, 0.80829524],
       [0.79502396, 0.94715249, 0.67198139],
       [0.17148632, 0.52198012, 0.45893516],
       [0.8485364 , 0.20665538, 0.75978627]])

In [ ]:
play.dtype

dtype('float64')

hi!!! Now i am going to recall the above concepts

1.   Install, import and check version
2.   Different ways of creating a numpy array, check type
3.   Creating 1,2,3 and multi dimension array
4.   Create array with zeros and Ones.  
5.   Create array with unitialzed values, and with constant (empty,full)
6.   Create a 1,2-D identity, and a flexible identity array (eye, identity)
7.   Create an array with spaced elements  ( arange, linspace)
8.   Create array with random intergers in a range (random, mean,std)
9.   Change array value type with astype()
10.  Can i loop over a numpy array?
11.  Perform operations add, subs, multiply, div
12.  Accessing elements of numpy array

In [ ]:
# Install, import and check version
!pip install numpy

In [1]:
import numpy as np
np.__version__

'2.0.2'

## Different ways of creating a numpy array.
*create array with empty, zeros, ones,constant values, eye, identity, arange, linspace, random number(int,float)*

In [ ]:
# Create with list and tuple
listarray = np.array([2,34,1,1]) #list
print(listarray)
tuplearray = np.array((1,4,2,6,2))
print(tuplearray)

[ 2 34  1  1]
[1 4 2 6 2]


In [ ]:
# create with zero's, one's
#
d1zeroarray = np.zeros(5)

print("1-D zeroarray")
print(d1zeroarray)
zeroarry = np.zeros(5, int)
print("1-D zeroarray with data types specified")
print(zeroarray)
zeroarray = np.zeros((3,4)) #2D array with tuple of int
print("2D zeroarray")
print(zeroarray)
onearray  = np.ones((2,5),int)
print("2D onearray with data type\n",onearray)

1-D zeroarray
[0. 0. 0. 0. 0.]
1-D zeroarray with data types specified
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D zeroarray
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D onearray with data type
 [[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#create array with empty
emptyarray = np.empty(5)
print(emptyarray)
emptyarray = np.empty((3,4))
print("emptyarray with shape\n", emptyarray)

[0. 0. 0. 0. 0.]
emptyarray with shape
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# create  a filed array with constant
constantnoarray = np.full((4,4),3)
print(constantnoarray)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
# create array with eye and identity
identityarray = np.identity(5,int)
print(identityarray)
eyearray= np.eye(5,3)
eyearray

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# arange and linspace
arangearray = np.arange(2 , 20 ,3) #start, stop,step
print(arangearray )
linspacearray = np.linspace(3,13,5) #start,stop, no. of values required
linspacearray

[ 2  5  8 11 14 17]


array([ 3. ,  5.5,  8. , 10.5, 13. ])

In [ ]:
# random array
randomarray = np.random.randint(3,8, (3,3))
print(randomarray)

[[3 5 4]
 [5 4 4]
 [5 3 4]]


In [10]:
arr1d = np.array ( [2,34,5,65,1])
arr2d = np.array ([[2,3,4],[4,6,7]])

arr = np.array([[[23,24,1],[54,23,7]],
                  [[8,12,4],[3,2,0]]
                ])
print(arr1d.ndim)
print(arr2d.ndim)
print(arr.ndim)
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

1
2
3
[[[[[1 2 3 4]]]]]


In [2]:
# !pip install numpy
import numpy as np
# np.__version__
array1 = np.array([1,2,35,6,1,3])
array2 = np.array((2,35,32,13,))
array3 = np.zeros((4,5)) # only (5) means 1x5 i..e 5 values in 1D array
array4 = np.ones(4,int) # 1x4 values of interger type, bydefault its float type for ones and zeros
array5 = np.empty(3)
# filed with constant, eye,identity
array6 = np.full([5,1],45)
array7 = np.eye(N=6,M= 6,k=0, dtype=int)
array8 = np.identity(5,dtype= int)
array9 = np.arange(0,40,7)
array10 = np.linspace(0,40,10,dtype= int)
array11 = np.random.rand(2,3)
array12 = np.random.randint(low=3, high= 12, size=[3,5,2],)
# standard deviotion with random randn, test other randoms
array13 = np.random.randn(12,3,)
array14 = 3 + 2.5 *(np.random.randn(4,3))
print(array14)
print(np.mean(array14))
print(np.std(array14))

[[5.55186477 4.74990824 1.11547114]
 [0.75950994 5.35678137 8.7985338 ]
 [0.48751321 7.45243775 2.9793687 ]
 [0.77375882 0.7157796  1.10364014]]
3.3203806236299163
2.8284026109588147


In [ ]:
#print type of array1 and convert to someother datatype with (astype)
print(array1.dtype)
np.astype(array1, np.float64 ) # copy array one, convert values to float )

int64


array([ 1.,  2., 35.,  6.,  1.,  3.])

In [ ]:
np.random.choice(10,5,0) #stop,no. of values, 0 = no repeat | 1 =repeat

array([5, 7, 8, 1, 4])

In [ ]:
# Want to reproduce same results with random
np.random.seed(42) #set a seed
array15 = np.random.rand(3)

array16 = np.random.rand(3)

#activate same seed again
np.random.seed(42)
array17 = np.random.rand(3)


In [ ]:
print('array15 with seed(42): ', array15)
print('array16 without seed: ', array16)
print('array17 with same seed(42): ', array17)

array15 with seed(42):  [0.37454012 0.95071431 0.73199394]
array16 without seed:  [0.59865848 0.15601864 0.15599452]
array17 with same seed(42):  [0.37454012 0.95071431 0.73199394]


Operations:

*   max , min, argmax argmin
*   shape, reshape , transform